language: node_js
node_js: lts/*

notifications:
  email: false

cache:
  directories:
    - node_modules
    - ~/.nvmrc

install:
  - npm install
  - npm run build

stages:
  - tests and pre-checks
  - name: deployment
    if: branch = master

jobs:
  include:
    # Linting
    - stage: tests and pre-checks
      env: DO=linting
      script: npm run lint

    # Depenedency checking
    - stage: tests and pre-checks
      env: DO=dependency-checking
      script:
        - npm i -g snyk
        - snyk test

    # Unit tests
    - stage: tests and pre-checks
      node_js: 8
      env: DO=unit-testing
      script: npm test

    - stage: tests and pre-checks
      node_js: 6
      env: DO=unit-testing
      script: npm test

    # Deploy
    - stage: deployment
      env: DO=publishing
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
