language: node_js

notifications:
  email: false

cache:
  directories:
    - node_modules
    - ~/.nvmrc

install:
  - npm install
  - npm run build

jobs:
  include:
    - stage: test
      node_js: lts/*
      env:
        - STAGE=lint
      script: npm run lint
    - stage: test
      node_js: 8
      script: npm test
    - stage: test
      node_js: 6
      script: npm test
    - stage: release
      script: skip
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run release
        on:
          branch: master
