language: node_js
notifications:
  email: false

jobs:
  include:
    - stage: test
      node_js: 8
      script: npm run test
      node_js: 6
      script: npm run test
    - stage: publish
      script: skip
      node_js: 8
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run release
        on:
          branch: master
