language: node_js
notifications:
  email: false

cache:
  directories:
    - node_modules
    - ~/.nvmrc

install:
  - npm install
  - npm run build


jobs:
  include:
    - stage: test
      node_js: 8
      script: npm run lint
    - stage: test
      node_js: 8
    - stage: test
      node_js: 6
    - stage: release
      script: skip
      node_js: 8
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run release
        on:
          branch: master
