language: node_js

node_js:
  - 8
  - 6

script:
- npm i
- npm run build
- npm test

jobs:
  include:
    - script: npm i
    - script: npm run build
    - stage: publish
      script: skip
      node_js: 8
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - echo $TEST_VAR
        on:
          branch: master
