language: node_js

node_js:
  - 8
  - 6

jobs:
  include:
    - stage: publish
      node_js: 8
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - echo $TEST_VAR
        on:
          branch: master
