language: node_js

jobs:
  include:
    - stage: test
      node_js:
        - 8
        - 6

      script:
      - npm i
      - npm run build
      - npm test
    - stage: publish
      script: skip
      node_js: 8
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - echo $TEST_VAR
        on:
          branch: master
