language: node_js
node_js: lts/*

notifications:
  email: false

cache:
  directories:
    - node_modules
    - ~/.nvmrc

install:
  - npm install
  - npm run build

jobs:
  include:
    - stage: test
      env: JOB=lint
      script: npm run lint
    - stage: test
      node_js: 8
      env: JOB=unit-test
      script: npm test
    - stage: test
      node_js: 6
      env: JOB=unit-test
      script: npm test
    - stage: release
      env: JOB=publish
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run release
        on:
          branch: master
