language: node_js

node_js:
  - 8
  - 6

script:
- npm --silent run build
- npm --silent test

jobs:
  include:
    - stage: publish
      script: skip
      node_js: 8
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run build
          - npx semantic-release
        on:
          branch: master
