language: node_js
notifications:
  email: false

install:
  - npm install
  - npm run build




jobs:
  include:
    - stage: lint
      node_js: 8
      script: npm run lint
      cache:
        directories:
          - node_modules
          - ~/.nvmrc
    - stage: test
      node_js:
        - 8
        - 6
      script: npm test
    - stage: release
      script: skip
      node_js: 8
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run release
        on:
          branch: master
