language: node_js

node_js:
  # - 10
  # - 9
  - 8
  # - 7
  - 6

cache:
  directories:
  - node_modules
  - ~/.npm

notifications:
  email: false

script:
- npm --silent run build
- npm --silent test:unit
- npm --silent test:lint

jobs:
  include:
    - stage: publish
      script: skip
      node_js: 8
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run release
        on:
          branch: master
